In [1]:
import tensorflow as tf

In [2]:
# 1. 가지고 있는 파일들이 몇개인가 리스트로 만듬
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
# 2. 파일을 읽어올 Reader를 결정
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
# 3. value를 어떻게 파싱할 것인가
# record_defaluts와 같이 각각의 필드의 값이 어떤 데이터 값인지 정해줄 수 있음
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
# batch는 펌프로 빨아들이듯이 데이터 읽어와서 변수에 부여, 앞이 Xdata, 뒤가 Ydata / batch_Size는 펌프할때마다 한번에 몇개씩 가져올 것인가
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLin

In [3]:
# 행렬간 곱셈해주는 함수 matmul
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# coord = 멀티쓰레드가 함께 종료될 수 있도록 도와주고 예외처리를 할 수 있도록 제공한다
coord = tf.train.Coordinator()
# 동일한 큐안에서 tensor가 동작할 수 있도록 쓰레드를 생성하는데 도움을 준다
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
for step in range(2001) :
    # 펌프질해서 데이터 가져온다
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    # 학습시킬때 X값 Y값으로 넘겨준다
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_batch, Y:y_batch})
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop() #쓰레드를 멈추도록 요청한다
coord.join(threads) # 쓰레드가 멈출때까지 기다린다

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost :  1297.8362 
Prediction:
 [[113.20863 ]
 [146.71422 ]
 [138.86047 ]
 [150.77997 ]
 [115.463104]
 [ 86.76737 ]
 [110.048386]
 [ 77.07726 ]
 [139.60416 ]
 [130.00772 ]]
10 Cost :  37.965836 
Prediction:
 [[149.16122 ]
 [189.90578 ]
 [181.4278  ]
 [197.14388 ]
 [148.39468 ]
 [111.05165 ]
 [144.7663  ]
 [102.833626]
 [179.97102 ]
 [167.40622 ]]
20 Cost :  38.589172 
Prediction:
 [[149.4148 ]
 [190.18355]
 [181.71512]
 [197.46024]
 [148.597  ]
 [111.20297]
 [145.01581]
 [103.03716]
 [180.2286 ]
 [167.65002]]
30 Cost :  38.41879 
Prediction:
 [[149.42741 ]
 [190.1718  ]
 [181.71712 ]
 [197.46585 ]
 [148.57849 ]
 [111.19148 ]
 [145.03267 ]
 [103.068184]
 [180.21555 ]
 [167.64311 ]]
40 Cost :  38.243465 
Prediction:
 [[149.43837]
 [190.15808]
 [181.7172 ]
 [197.46936]
 [148.55853]
 [111.17892]
 [145.04793]
 [103.09795]
 [180.20068]
 [167.63452]]
50 Cost :  38.069046 
Prediction:
 [[149.4493 ]
 [190.14442

510 Cost :  30.947742 
Prediction:
 [[149.92192 ]
 [189.55217 ]
 [181.71944 ]
 [197.62431 ]
 [147.67537 ]
 [110.62448 ]
 [145.72412 ]
 [104.417534]
 [179.54549 ]
 [167.25883 ]]
520 Cost :  30.81102 
Prediction:
 [[149.93155 ]
 [189.54005 ]
 [181.71945 ]
 [197.62743 ]
 [147.6577  ]
 [110.613434]
 [145.73767 ]
 [104.44398 ]
 [179.53242 ]
 [167.2514  ]]
530 Cost :  30.674967 
Prediction:
 [[149.9412 ]
 [189.52797]
 [181.7195 ]
 [197.63052]
 [147.64008]
 [110.6024 ]
 [145.7512 ]
 [104.47035]
 [179.5194 ]
 [167.244  ]]
540 Cost :  30.539536 
Prediction:
 [[149.95078]
 [189.5159 ]
 [181.71951]
 [197.6336 ]
 [147.62248]
 [110.59139]
 [145.76468]
 [104.49668]
 [179.5064 ]
 [167.2366 ]]
550 Cost :  30.404953 
Prediction:
 [[149.96036]
 [189.50389]
 [181.71956]
 [197.6367 ]
 [147.60495]
 [110.58044]
 [145.77814]
 [104.52293]
 [179.49342]
 [167.22926]]
560 Cost :  30.27102 
Prediction:
 [[149.96991]
 [189.49193]
 [181.71959]
 [197.63979]
 [147.58745]
 [110.56949]
 [145.79156]
 [104.54911]
 [179.4

1050 Cost :  24.48907 
Prediction:
 [[150.40816]
 [188.94037]
 [181.72029]
 [197.78156]
 [146.78229]
 [110.06744]
 [146.41016]
 [105.75605]
 [178.88727]
 [166.88782]]
1060 Cost :  24.385687 
Prediction:
 [[150.41652]
 [188.92981]
 [181.72029]
 [197.78429]
 [146.76686]
 [110.05785]
 [146.42201]
 [105.77918]
 [178.87593]
 [166.88148]]
1070 Cost :  24.282885 
Prediction:
 [[150.42488]
 [188.91928]
 [181.7203 ]
 [197.787  ]
 [146.7515 ]
 [110.0483 ]
 [146.43384]
 [105.80227]
 [178.86465]
 [166.8752 ]]
1080 Cost :  24.180529 
Prediction:
 [[150.4332  ]
 [188.90878 ]
 [181.72029 ]
 [197.78969 ]
 [146.73615 ]
 [110.038765]
 [146.44563 ]
 [105.825294]
 [178.85338 ]
 [166.8689  ]]
1090 Cost :  24.078781 
Prediction:
 [[150.4415 ]
 [188.89832]
 [181.7203 ]
 [197.7924 ]
 [146.72086]
 [110.02927]
 [146.45743]
 [105.84827]
 [178.84215]
 [166.86264]]
1100 Cost :  23.97754 
Prediction:
 [[150.44978]
 [188.88788]
 [181.7203 ]
 [197.79509]
 [146.7056 ]
 [110.01978]
 [146.46916]
 [105.87118]
 [178.83095

1610 Cost :  19.452522 
Prediction:
 [[150.84456 ]
 [188.38908 ]
 [181.71983 ]
 [197.92393 ]
 [145.97633 ]
 [109.567924]
 [147.03123 ]
 [106.967606]
 [178.29709 ]
 [166.5609  ]]
1620 Cost :  19.375233 
Prediction:
 [[150.85178 ]
 [188.37993 ]
 [181.71982 ]
 [197.92633 ]
 [145.96295 ]
 [109.559654]
 [147.04155 ]
 [106.987755]
 [178.28731 ]
 [166.55554 ]]
1630 Cost :  19.298351 
Prediction:
 [[150.85898]
 [188.3708 ]
 [181.7198 ]
 [197.9287 ]
 [145.9496 ]
 [109.55141]
 [147.05185]
 [107.00784]
 [178.27757]
 [166.55019]]
1640 Cost :  19.221869 
Prediction:
 [[150.86618 ]
 [188.36171 ]
 [181.71979 ]
 [197.93103 ]
 [145.9363  ]
 [109.54318 ]
 [147.06213 ]
 [107.027885]
 [178.26785 ]
 [166.54486 ]]
1650 Cost :  19.145796 
Prediction:
 [[150.87334]
 [188.35265]
 [181.71977]
 [197.9334 ]
 [145.92302]
 [109.53498]
 [147.07239]
 [107.04788]
 [178.25816]
 [166.53954]]
1660 Cost :  19.07011 
Prediction:
 [[150.8805 ]
 [188.3436 ]
 [181.71976]
 [197.93575]
 [145.90977]
 [109.5268 ]
 [147.08261]
 [1

In [ ]:
# 배치의 순서를 셔플하고 싶을때
min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch([example, label], batch_size=batch_size, capacity=capacity,min_after_dequeue=min_after_dequeue)
