In [4]:
import tensorflow as tf
import numpy as np

In [5]:
tf.set_random_seed(777)  # for reproducibility

In [6]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [7]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# min-max 정규화
xy = min_max_scaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost) 

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  0.7992051 
Prediction:
 [[ 0.47259712]
 [ 0.23193526]
 [-0.15399647]
 [-0.5640317 ]
 [-0.3167944 ]
 [-0.42378223]
 [-1.0409808 ]
 [-1.0878552 ]]
1 Cost:  0.799157 
Prediction:
 [[ 0.47263503]
 [ 0.23197353]
 [-0.15396416]
 [-0.564006  ]
 [-0.3167646 ]
 [-0.42375332]
 [-1.0409598 ]
 [-1.0878341 ]]
2 Cost:  0.7991088 
Prediction:
 [[ 0.47267294]
 [ 0.23201168]
 [-0.15393174]
 [-0.5639803 ]
 [-0.3167348 ]
 [-0.4237244 ]
 [-1.0409387 ]
 [-1.0878129 ]]
3 Cost:  0.7990605 
Prediction:
 [[ 0.47271085]
 [ 0.23205006]
 [-0.153899

74 Cost:  0.7956467 
Prediction:
 [[ 0.47539687]
 [ 0.23476171]
 [-0.15160418]
 [-0.5621296 ]
 [-0.31459117]
 [-0.421642  ]
 [-1.0394236 ]
 [-1.0862918 ]]
75 Cost:  0.7955987 
Prediction:
 [[ 0.47543478]
 [ 0.23479998]
 [-0.15157187]
 [-0.5621039 ]
 [-0.31456143]
 [-0.42161304]
 [-1.0394025 ]
 [-1.0862707 ]]
76 Cost:  0.7955507 
Prediction:
 [[ 0.47547257]
 [ 0.23483813]
 [-0.15153956]
 [-0.5620782 ]
 [-0.31453162]
 [-0.42158413]
 [-1.0393815 ]
 [-1.0862496 ]]
77 Cost:  0.7955028 
Prediction:
 [[ 0.47551036]
 [ 0.23487628]
 [-0.15150726]
 [-0.5620525 ]
 [-0.31450188]
 [-0.42155522]
 [-1.0393605 ]
 [-1.0862285 ]]
78 Cost:  0.79545474 
Prediction:
 [[ 0.47554827]
 [ 0.23491454]
 [-0.15147495]
 [-0.56202686]
 [-0.31447208]
 [-0.42152625]
 [-1.0393394 ]
 [-1.0862074 ]]
79 Cost:  0.7954067 
Prediction:
 [[ 0.47558606]
 [ 0.23495257]
 [-0.15144265]
 [-0.5620011 ]
 [-0.31444234]
 [-0.4214974 ]
 [-1.0393183 ]
 [-1.0861862 ]]
80 Cost:  0.7953588 
Prediction:
 [[ 0.47562385]
 [ 0.23499084]
 [-0.

205 Cost:  0.7893889 
Prediction:
 [[ 0.48034132]
 [ 0.23975205]
 [-0.14738059]
 [-0.5587715 ]
 [-0.31070137]
 [-0.4178635 ]
 [-1.0366751 ]
 [-1.083533  ]]
206 Cost:  0.78934145 
Prediction:
 [[ 0.480379  ]
 [ 0.23978996]
 [-0.14734852]
 [-0.5587459 ]
 [-0.3106718 ]
 [-0.4178347 ]
 [-1.0366542 ]
 [-1.0835121 ]]
207 Cost:  0.7892939 
Prediction:
 [[ 0.48041666]
 [ 0.23982811]
 [-0.14731622]
 [-0.55872035]
 [-0.31064212]
 [-0.4178059 ]
 [-1.0366333 ]
 [-1.0834911 ]]
208 Cost:  0.78924644 
Prediction:
 [[ 0.48045433]
 [ 0.23986602]
 [-0.14728415]
 [-0.5586948 ]
 [-0.3106125 ]
 [-0.41777706]
 [-1.0366124 ]
 [-1.0834701 ]]
209 Cost:  0.7891989 
Prediction:
 [[ 0.480492  ]
 [ 0.23990405]
 [-0.14725196]
 [-0.5586692 ]
 [-0.31058288]
 [-0.41774845]
 [-1.0365915 ]
 [-1.0834491 ]]
210 Cost:  0.7891513 
Prediction:
 [[ 0.48052967]
 [ 0.23994207]
 [-0.14721978]
 [-0.5586436 ]
 [-0.31055325]
 [-0.4177196 ]
 [-1.0365705 ]
 [-1.0834281 ]]
211 Cost:  0.78910375 
Prediction:
 [[ 0.48056734]
 [ 0.239979

321 Cost:  0.7838998 
Prediction:
 [[ 0.48469508]
 [ 0.24414802]
 [-0.14365947]
 [-0.555812  ]
 [-0.3072741 ]
 [-0.4145341 ]
 [-1.0342513 ]
 [-1.0810999 ]]
322 Cost:  0.7838526 
Prediction:
 [[ 0.4847325 ]
 [ 0.2441858 ]
 [-0.1436274 ]
 [-0.55578655]
 [-0.30724454]
 [-0.41450536]
 [-1.0342305 ]
 [-1.0810789 ]]
323 Cost:  0.7838055 
Prediction:
 [[ 0.48476994]
 [ 0.2442236 ]
 [-0.14359546]
 [-0.55576104]
 [-0.3072151 ]
 [-0.4144767 ]
 [-1.0342096 ]
 [-1.081058  ]]
324 Cost:  0.78375834 
Prediction:
 [[ 0.48480737]
 [ 0.24426138]
 [-0.14356339]
 [-0.5557356 ]
 [-0.30718553]
 [-0.41444808]
 [-1.0341887 ]
 [-1.081037  ]]
325 Cost:  0.78371125 
Prediction:
 [[ 0.4848448 ]
 [ 0.24429917]
 [-0.14353144]
 [-0.55571014]
 [-0.3071561 ]
 [-0.4144194 ]
 [-1.0341679 ]
 [-1.0810161 ]]
326 Cost:  0.78366405 
Prediction:
 [[ 0.48488224]
 [ 0.24433708]
 [-0.14349937]
 [-0.5556846 ]
 [-0.30712652]
 [-0.41439068]
 [-1.034147  ]
 [-1.0809951 ]]
327 Cost:  0.7836169 
Prediction:
 [[ 0.48491967]
 [ 0.244374

436 Cost:  0.7785102 
Prediction:
 [[ 0.48898792]
 [ 0.2484833 ]
 [-0.13998997]
 [-0.552894  ]
 [-0.30389464]
 [-0.4112509 ]
 [-1.0318615 ]
 [-1.0786998 ]]
437 Cost:  0.77846354 
Prediction:
 [[ 0.48902512]
 [ 0.24852085]
 [-0.13995814]
 [-0.5528687 ]
 [-0.3038653 ]
 [-0.41122234]
 [-1.0318408 ]
 [-1.078679  ]]
438 Cost:  0.77841693 
Prediction:
 [[ 0.4890623 ]
 [ 0.24855852]
 [-0.13992631]
 [-0.5528434 ]
 [-0.303836  ]
 [-0.41119385]
 [-1.03182   ]
 [-1.0786581 ]]
439 Cost:  0.77837026 
Prediction:
 [[ 0.4890995 ]
 [ 0.24859619]
 [-0.13989449]
 [-0.55281806]
 [-0.30380666]
 [-0.41116542]
 [-1.0317993 ]
 [-1.0786372 ]]
440 Cost:  0.77832365 
Prediction:
 [[ 0.48913682]
 [ 0.24863374]
 [-0.13986266]
 [-0.5527927 ]
 [-0.30377734]
 [-0.41113693]
 [-1.0317786 ]
 [-1.0786165 ]]
441 Cost:  0.778277 
Prediction:
 [[ 0.489174  ]
 [ 0.2486713 ]
 [-0.13983083]
 [-0.55276746]
 [-0.30374807]
 [-0.41110837]
 [-1.0317578 ]
 [-1.0785956 ]]
442 Cost:  0.7782303 
Prediction:
 [[ 0.4892112 ]
 [ 0.248708

555 Cost:  0.77297217 
Prediction:
 [[ 0.49341595]
 [ 0.25295544]
 [-0.13620365]
 [-0.5498818 ]
 [-0.30040705]
 [-0.40786272]
 [-1.0293933 ]
 [-1.0762218 ]]
556 Cost:  0.772926 
Prediction:
 [[ 0.49345303]
 [ 0.25299287]
 [-0.13617206]
 [-0.54985666]
 [-0.30037785]
 [-0.4078344 ]
 [-1.0293727 ]
 [-1.0762011 ]]
557 Cost:  0.7728798 
Prediction:
 [[ 0.4934901 ]
 [ 0.2530303 ]
 [-0.13614023]
 [-0.54983145]
 [-0.3003487 ]
 [-0.40780604]
 [-1.0293521 ]
 [-1.0761805 ]]
558 Cost:  0.7728336 
Prediction:
 [[ 0.49352717]
 [ 0.25306773]
 [-0.13610864]
 [-0.5498063 ]
 [-0.30031955]
 [-0.40777773]
 [-1.0293314 ]
 [-1.0761597 ]]
559 Cost:  0.77278733 
Prediction:
 [[ 0.49356425]
 [ 0.25310516]
 [-0.13607693]
 [-0.5497811 ]
 [-0.3002903 ]
 [-0.40774935]
 [-1.029311  ]
 [-1.076139  ]]
560 Cost:  0.77274114 
Prediction:
 [[ 0.49360132]
 [ 0.2531426 ]
 [-0.13604522]
 [-0.5497559 ]
 [-0.30026114]
 [-0.40772104]
 [-1.0292902 ]
 [-1.0761184 ]]
561 Cost:  0.77269495 
Prediction:
 [[ 0.4936384 ]
 [ 0.253180

674 Cost:  0.7674924 
Prediction:
 [[ 0.4978187 ]
 [ 0.25740218]
 [-0.13243961]
 [-0.5468885 ]
 [-0.29694045]
 [-0.40449512]
 [-1.0269414 ]
 [-1.0737599 ]]
675 Cost:  0.76744664 
Prediction:
 [[ 0.49785554]
 [ 0.25743937]
 [-0.13240814]
 [-0.5468633 ]
 [-0.29691142]
 [-0.40446693]
 [-1.0269208 ]
 [-1.0737393 ]]
676 Cost:  0.76740074 
Prediction:
 [[ 0.49789238]
 [ 0.2574767 ]
 [-0.13237655]
 [-0.5468382 ]
 [-0.29688227]
 [-0.4044386 ]
 [-1.0269003 ]
 [-1.0737185 ]]
677 Cost:  0.76735497 
Prediction:
 [[ 0.49792933]
 [ 0.25751388]
 [-0.13234496]
 [-0.54681313]
 [-0.2968533 ]
 [-0.40441042]
 [-1.0268797 ]
 [-1.0736979 ]]
678 Cost:  0.76730907 
Prediction:
 [[ 0.49796617]
 [ 0.25755107]
 [-0.13231349]
 [-0.54678804]
 [-0.29682422]
 [-0.40438223]
 [-1.026859  ]
 [-1.0736772 ]]
679 Cost:  0.7672633 
Prediction:
 [[ 0.498003  ]
 [ 0.2575884 ]
 [-0.1322819 ]
 [-0.54676294]
 [-0.2967952 ]
 [-0.40435398]
 [-1.0268385 ]
 [-1.0736566 ]]
680 Cost:  0.7672174 
Prediction:
 [[ 0.49803996]
 [ 0.25762

800 Cost:  0.76173985 
Prediction:
 [[ 0.50245655]
 [ 0.26208854]
 [-0.12847173]
 [-0.54373145]
 [-0.2932858 ]
 [-0.4009441 ]
 [-1.0243531 ]
 [-1.0711598 ]]
801 Cost:  0.76169455 
Prediction:
 [[ 0.50249314]
 [ 0.26212573]
 [-0.12844038]
 [-0.5437065 ]
 [-0.29325688]
 [-0.4009161 ]
 [-1.0243328 ]
 [-1.0711393 ]]
802 Cost:  0.76164913 
Prediction:
 [[ 0.50253   ]
 [ 0.2621628 ]
 [-0.12840903]
 [-0.5436815 ]
 [-0.2932279 ]
 [-0.40088797]
 [-1.0243123 ]
 [-1.0711188 ]]
803 Cost:  0.7616038 
Prediction:
 [[ 0.5025666 ]
 [ 0.26219988]
 [-0.12837756]
 [-0.5436565 ]
 [-0.293199  ]
 [-0.40085983]
 [-1.0242918 ]
 [-1.0710983 ]]
804 Cost:  0.7615584 
Prediction:
 [[ 0.5026034 ]
 [ 0.26223695]
 [-0.12834609]
 [-0.54363155]
 [-0.2931701 ]
 [-0.40083182]
 [-1.0242714 ]
 [-1.0710777 ]]
805 Cost:  0.761513 
Prediction:
 [[ 0.50264   ]
 [ 0.26227403]
 [-0.12831473]
 [-0.54360664]
 [-0.2931412 ]
 [-0.4008037 ]
 [-1.0242509 ]
 [-1.0710572 ]]
806 Cost:  0.7614677 
Prediction:
 [[ 0.5026767 ]
 [ 0.2623111

934 Cost:  0.7556802 
Prediction:
 [[ 0.50736654]
 [ 0.26704955]
 [-0.12427115]
 [-0.54038936]
 [-0.28941667]
 [-0.39718533]
 [-1.0216134 ]
 [-1.0684086 ]]
935 Cost:  0.7556351 
Prediction:
 [[ 0.50740314]
 [ 0.2670865 ]
 [-0.12423992]
 [-0.5403644 ]
 [-0.28938782]
 [-0.39715725]
 [-1.0215929 ]
 [-1.0683881 ]]
936 Cost:  0.75558996 
Prediction:
 [[ 0.50743973]
 [ 0.26712358]
 [-0.12420857]
 [-0.54033947]
 [-0.28935897]
 [-0.3971293 ]
 [-1.0215724 ]
 [-1.0683676 ]]
937 Cost:  0.7555449 
Prediction:
 [[ 0.50747633]
 [ 0.26716053]
 [-0.12417722]
 [-0.54031456]
 [-0.28933012]
 [-0.39710122]
 [-1.021552  ]
 [-1.068347  ]]
938 Cost:  0.75549984 
Prediction:
 [[ 0.5075129 ]
 [ 0.2671975 ]
 [-0.12414587]
 [-0.54028964]
 [-0.28930128]
 [-0.3970732 ]
 [-1.0215316 ]
 [-1.0683265 ]]
939 Cost:  0.7554548 
Prediction:
 [[ 0.5075495 ]
 [ 0.26723444]
 [-0.12411463]
 [-0.5402647 ]
 [-0.28927243]
 [-0.3970452 ]
 [-1.0215111 ]
 [-1.068306  ]]
940 Cost:  0.7554097 
Prediction:
 [[ 0.5075861 ]
 [ 0.2672714

1051 Cost:  0.7504399 
Prediction:
 [[ 0.51163197]
 [ 0.2713598 ]
 [-0.12062168]
 [-0.5374857 ]
 [-0.28605533]
 [-0.39391953]
 [-1.0192327 ]
 [-1.0660176 ]]
1052 Cost:  0.75039536 
Prediction:
 [[ 0.5116683 ]
 [ 0.27139652]
 [-0.12059057]
 [-0.537461  ]
 [-0.2860266 ]
 [-0.39389175]
 [-1.0192125 ]
 [-1.0659972 ]]
1053 Cost:  0.7503508 
Prediction:
 [[ 0.51170456]
 [ 0.27143323]
 [-0.12055945]
 [-0.53743625]
 [-0.285998  ]
 [-0.39386392]
 [-1.0191922 ]
 [-1.0659769 ]]
1054 Cost:  0.75030625 
Prediction:
 [[ 0.5117409 ]
 [ 0.27146995]
 [-0.12052834]
 [-0.5374116 ]
 [-0.28596938]
 [-0.39383608]
 [-1.019172  ]
 [-1.0659566 ]]
1055 Cost:  0.7502617 
Prediction:
 [[ 0.5117773 ]
 [ 0.2715068 ]
 [-0.12049735]
 [-0.53738683]
 [-0.28594077]
 [-0.39380825]
 [-1.0191517 ]
 [-1.0659361 ]]
1056 Cost:  0.75021726 
Prediction:
 [[ 0.51181364]
 [ 0.27154338]
 [-0.12046623]
 [-0.53736204]
 [-0.28591216]
 [-0.39378047]
 [-1.0191314 ]
 [-1.0659157 ]]
1057 Cost:  0.7501727 
Prediction:
 [[ 0.51185   ]
 [ 0

1168 Cost:  0.7452444 
Prediction:
 [[ 0.51587415]
 [ 0.27564943]
 [-0.1169889 ]
 [-0.5345942 ]
 [-0.282709  ]
 [-0.39066803]
 [-1.0168598 ]
 [-1.0636333 ]]
1169 Cost:  0.74520004 
Prediction:
 [[ 0.5159104 ]
 [ 0.2756859 ]
 [-0.1169579 ]
 [-0.53456944]
 [-0.2826804 ]
 [-0.3906402 ]
 [-1.0168395 ]
 [-1.0636129 ]]
1170 Cost:  0.74515593 
Prediction:
 [[ 0.5159466 ]
 [ 0.27572262]
 [-0.11692691]
 [-0.53454477]
 [-0.28265178]
 [-0.39061248]
 [-1.0168192 ]
 [-1.0635927 ]]
1171 Cost:  0.7451116 
Prediction:
 [[ 0.51598287]
 [ 0.2757591 ]
 [-0.11689579]
 [-0.53452003]
 [-0.2826233 ]
 [-0.3905847 ]
 [-1.016799  ]
 [-1.0635723 ]]
1172 Cost:  0.7450673 
Prediction:
 [[ 0.5160191 ]
 [ 0.27579582]
 [-0.1168648 ]
 [-0.53449535]
 [-0.28259468]
 [-0.39055693]
 [-1.0167787 ]
 [-1.0635519 ]]
1173 Cost:  0.7450231 
Prediction:
 [[ 0.51605535]
 [ 0.27583253]
 [-0.11683381]
 [-0.5344707 ]
 [-0.2825662 ]
 [-0.39052922]
 [-1.0167584 ]
 [-1.0635315 ]]
1174 Cost:  0.7449788 
Prediction:
 [[ 0.5160916 ]
 [ 0.

1276 Cost:  0.7404914 
Prediction:
 [[ 0.5197749 ]
 [ 0.27959204]
 [-0.11365056]
 [-0.53193784]
 [-0.27963424]
 [-0.38768053]
 [-1.0146813 ]
 [-1.0614451 ]]
1277 Cost:  0.7404476 
Prediction:
 [[ 0.5198109 ]
 [ 0.2796284 ]
 [-0.11361969]
 [-0.5319133 ]
 [-0.27960575]
 [-0.387653  ]
 [-1.0146612 ]
 [-1.0614249 ]]
1278 Cost:  0.7404038 
Prediction:
 [[ 0.5198469 ]
 [ 0.27966475]
 [-0.11358881]
 [-0.5318887 ]
 [-0.27957737]
 [-0.38762534]
 [-1.014641  ]
 [-1.0614047 ]]
1279 Cost:  0.7403599 
Prediction:
 [[ 0.5198829 ]
 [ 0.27970135]
 [-0.11355793]
 [-0.53186417]
 [-0.279549  ]
 [-0.38759768]
 [-1.0146209 ]
 [-1.0613844 ]]
1280 Cost:  0.7403161 
Prediction:
 [[ 0.5199189 ]
 [ 0.2797377 ]
 [-0.11352718]
 [-0.5318396 ]
 [-0.2795205 ]
 [-0.38757014]
 [-1.0146008 ]
 [-1.0613642 ]]
1281 Cost:  0.7402722 
Prediction:
 [[ 0.51995504]
 [ 0.27977407]
 [-0.1134963 ]
 [-0.53181505]
 [-0.27949202]
 [-0.3875425 ]
 [-1.0145806 ]
 [-1.0613439 ]]
1282 Cost:  0.74022835 
Prediction:
 [[ 0.51999104]
 [ 0.2

1393 Cost:  0.7353767 
Prediction:
 [[ 0.52398634]
 [ 0.28384936]
 [-0.11004424]
 [-0.52906656]
 [-0.27631176]
 [-0.3844527 ]
 [-1.0123248 ]
 [-1.0590787 ]]
1394 Cost:  0.7353332 
Prediction:
 [[ 0.5240222 ]
 [ 0.28388572]
 [-0.11001348]
 [-0.5290421 ]
 [-0.2762835 ]
 [-0.38442516]
 [-1.0123047 ]
 [-1.0590584 ]]
1395 Cost:  0.7352897 
Prediction:
 [[ 0.5240581 ]
 [ 0.28392208]
 [-0.10998273]
 [-0.52901757]
 [-0.27625525]
 [-0.38439763]
 [-1.0122845 ]
 [-1.0590383 ]]
1396 Cost:  0.7352463 
Prediction:
 [[ 0.52409387]
 [ 0.28395832]
 [-0.10995209]
 [-0.52899325]
 [-0.276227  ]
 [-0.3843702 ]
 [-1.0122645 ]
 [-1.0590181 ]]
1397 Cost:  0.735203 
Prediction:
 [[ 0.5241296 ]
 [ 0.28399444]
 [-0.10992146]
 [-0.5289689 ]
 [-0.27619874]
 [-0.3843428 ]
 [-1.0122446 ]
 [-1.058998  ]]
1398 Cost:  0.73515964 
Prediction:
 [[ 0.5241654 ]
 [ 0.28403068]
 [-0.10989082]
 [-0.5289445 ]
 [-0.2761705 ]
 [-0.38431543]
 [-1.0122246 ]
 [-1.058978  ]]
1399 Cost:  0.73511636 
Prediction:
 [[ 0.52420115]
 [ 0.2

1515 Cost:  0.7301055 
Prediction:
 [[ 0.528345  ]
 [ 0.2882582 ]
 [-0.10631073]
 [-0.5260951 ]
 [-0.27287304]
 [-0.38111103]
 [-1.0098858 ]
 [-1.0566272 ]]
1516 Cost:  0.7300624 
Prediction:
 [[ 0.52838075]
 [ 0.2882942 ]
 [-0.10628021]
 [-0.5260707 ]
 [-0.2728449 ]
 [-0.38108367]
 [-1.0098658 ]
 [-1.0566071 ]]
1517 Cost:  0.73001933 
Prediction:
 [[ 0.5284163 ]
 [ 0.2883302 ]
 [-0.10624969]
 [-0.5260464 ]
 [-0.27281678]
 [-0.38105637]
 [-1.0098457 ]
 [-1.056587  ]]
1518 Cost:  0.7299763 
Prediction:
 [[ 0.52845204]
 [ 0.28836644]
 [-0.10621905]
 [-0.5260221 ]
 [-0.27278864]
 [-0.381029  ]
 [-1.0098258 ]
 [-1.056567  ]]
1519 Cost:  0.72993326 
Prediction:
 [[ 0.52848756]
 [ 0.28840244]
 [-0.10618854]
 [-0.52599776]
 [-0.2727605 ]
 [-0.38100165]
 [-1.0098058 ]
 [-1.0565468 ]]
1520 Cost:  0.7298902 
Prediction:
 [[ 0.5285233 ]
 [ 0.28843844]
 [-0.1061579 ]
 [-0.52597344]
 [-0.27273238]
 [-0.3809743 ]
 [-1.0097859 ]
 [-1.0565268 ]]
1521 Cost:  0.72984713 
Prediction:
 [[ 0.52855885]
 [ 0

1638 Cost:  0.72482955 
Prediction:
 [[ 0.5327251 ]
 [ 0.2926886 ]
 [-0.10255766]
 [-0.5231067 ]
 [-0.26941574]
 [-0.3777516 ]
 [-1.0074315 ]
 [-1.0541614 ]]
1639 Cost:  0.7247869 
Prediction:
 [[ 0.5327606 ]
 [ 0.29272437]
 [-0.10252726]
 [-0.52308244]
 [-0.26938772]
 [-0.3777243 ]
 [-1.0074117 ]
 [-1.0541414 ]]
1640 Cost:  0.7247443 
Prediction:
 [[ 0.53279614]
 [ 0.29276037]
 [-0.10249686]
 [-0.52305824]
 [-0.2693597 ]
 [-0.37769717]
 [-1.0073919 ]
 [-1.0541215 ]]
1641 Cost:  0.72470164 
Prediction:
 [[ 0.53283167]
 [ 0.29279637]
 [-0.10246646]
 [-0.5230341 ]
 [-0.2693317 ]
 [-0.37766993]
 [-1.007372  ]
 [-1.0541015 ]]
1642 Cost:  0.7246591 
Prediction:
 [[ 0.5328671 ]
 [ 0.29283226]
 [-0.10243607]
 [-0.5230099 ]
 [-0.26930368]
 [-0.37764275]
 [-1.0073521 ]
 [-1.0540816 ]]
1643 Cost:  0.72461647 
Prediction:
 [[ 0.5329026 ]
 [ 0.29286814]
 [-0.10240567]
 [-0.5229857 ]
 [-0.26927567]
 [-0.3776155 ]
 [-1.0073323 ]
 [-1.0540617 ]]
1644 Cost:  0.72457385 
Prediction:
 [[ 0.5329381 ]
 [ 

1773 Cost:  0.7190955 
Prediction:
 [[ 0.53751016]
 [ 0.29752803]
 [-0.09845841]
 [-0.5198429 ]
 [-0.26563942]
 [-0.37408257]
 [-1.004752  ]
 [-1.0514698 ]]
1774 Cost:  0.71905327 
Prediction:
 [[ 0.53754544]
 [ 0.29756367]
 [-0.09842813]
 [-0.51981884]
 [-0.26561153]
 [-0.3740555 ]
 [-1.0047323 ]
 [-1.0514498 ]]
1775 Cost:  0.719011 
Prediction:
 [[ 0.5375807 ]
 [ 0.29759943]
 [-0.09839785]
 [-0.51979476]
 [-0.26558375]
 [-0.37402844]
 [-1.0047123 ]
 [-1.0514299 ]]
1776 Cost:  0.71896875 
Prediction:
 [[ 0.537616  ]
 [ 0.29763508]
 [-0.09836769]
 [-0.5197706 ]
 [-0.26555586]
 [-0.37400126]
 [-1.0046926 ]
 [-1.05141   ]]
1777 Cost:  0.71892655 
Prediction:
 [[ 0.5376513 ]
 [ 0.29767084]
 [-0.09833741]
 [-0.51974654]
 [-0.26552796]
 [-0.3739742 ]
 [-1.0046728 ]
 [-1.05139   ]]
1778 Cost:  0.71888435 
Prediction:
 [[ 0.5376866 ]
 [ 0.29770648]
 [-0.09830713]
 [-0.5197224 ]
 [-0.26550007]
 [-0.37394708]
 [-1.004653  ]
 [-1.0513701 ]]
1779 Cost:  0.718842 
Prediction:
 [[ 0.5377219 ]
 [ 0.

1897 Cost:  0.71388465 
Prediction:
 [[ 0.54187477]
 [ 0.30194533]
 [-0.09471631]
 [-0.516863  ]
 [-0.26219237]
 [-0.37073255]
 [-1.0023035 ]
 [-1.0490081 ]]
1898 Cost:  0.71384287 
Prediction:
 [[ 0.54190993]
 [ 0.30198085]
 [-0.09468627]
 [-0.516839  ]
 [-0.2621647 ]
 [-0.3707056 ]
 [-1.0022838 ]
 [-1.0489883 ]]
1899 Cost:  0.713801 
Prediction:
 [[ 0.5419451 ]
 [ 0.30201638]
 [-0.09465611]
 [-0.51681507]
 [-0.26213694]
 [-0.3706786 ]
 [-1.0022641 ]
 [-1.0489686 ]]
1900 Cost:  0.71375906 
Prediction:
 [[ 0.54198027]
 [ 0.30205202]
 [-0.09462607]
 [-0.51679105]
 [-0.26210916]
 [-0.37065166]
 [-1.0022445 ]
 [-1.0489486 ]]
1901 Cost:  0.7137173 
Prediction:
 [[ 0.54201543]
 [ 0.30208755]
 [-0.09459591]
 [-0.51676714]
 [-0.2620815 ]
 [-0.37062472]
 [-1.0022247 ]
 [-1.0489289 ]]
1902 Cost:  0.71367544 
Prediction:
 [[ 0.5420505 ]
 [ 0.3021232 ]
 [-0.09456575]
 [-0.5167431 ]
 [-0.26205373]
 [-0.37059772]
 [-1.002205  ]
 [-1.0489091 ]]
1903 Cost:  0.71363366 
Prediction:
 [[ 0.54208565]
 [ 