In [1]:
import tensorflow as tf

In [2]:
# 이런 방법은 수가 커지면 복잡해지므로 이제는 사용하지 않는다

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 +x2 * w2 + x3 * w3 + b

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001) :
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction:\n", hy_val)

0 Cost :  72063.38 
Prediction:
 [ -90.34958   -99.169815 -102.743225 -111.36539   -73.438835]
10 Cost :  6.7898893 
Prediction:
 [147.12178 186.23505 178.48044 194.87892 144.24971]
20 Cost :  6.09824 
Prediction:
 [147.84978 187.09207 179.33424 195.80746 144.89996]
30 Cost :  6.0664268 
Prediction:
 [147.86143 187.0882  179.33974 195.81226 144.89355]
40 Cost :  6.034762 
Prediction:
 [147.87091 187.08173 179.34267 195.81424 144.88518]
50 Cost :  6.0032625 
Prediction:
 [147.88034 187.07526 179.34558 195.8162  144.8768 ]
60 Cost :  5.971972 
Prediction:
 [147.88977 187.06885 179.34848 195.81818 144.86848]
70 Cost :  5.940818 
Prediction:
 [147.89915 187.06241 179.35138 195.82013 144.86017]
80 Cost :  5.9098215 
Prediction:
 [147.90852 187.056   179.35425 195.8221  144.85187]
90 Cost :  5.8790426 
Prediction:
 [147.91785 187.04962 179.35713 195.82404 144.8436 ]
100 Cost :  5.848382 
Prediction:
 [147.92717 187.04324 179.36002 195.82597 144.83536]
110 Cost :  5.817886 
Prediction:
 [147.

1170 Cost :  3.3659444 
Prediction:
 [148.79192 186.45187 179.6268  196.00465 144.0714 ]
1180 Cost :  3.348844 
Prediction:
 [148.79889 186.4471  179.62895 196.00609 144.06526]
1190 Cost :  3.3318715 
Prediction:
 [148.80583 186.44237 179.63109 196.00749 144.05914]
1200 Cost :  3.3149674 
Prediction:
 [148.81276 186.43762 179.63322 196.00893 144.05304]
1210 Cost :  3.298158 
Prediction:
 [148.81967 186.4329  179.63536 196.01033 144.04695]
1220 Cost :  3.2814472 
Prediction:
 [148.82657 186.4282  179.6375  196.01175 144.0409 ]
1230 Cost :  3.264814 
Prediction:
 [148.83344 186.4235  179.63962 196.01315 144.03484]
1240 Cost :  3.2482934 
Prediction:
 [148.84029 186.41882 179.64175 196.01456 144.02881]
1250 Cost :  3.231832 
Prediction:
 [148.84712 186.41414 179.64386 196.01593 144.02278]
1260 Cost :  3.215477 
Prediction:
 [148.85394 186.40948 179.64597 196.01733 144.01678]
1270 Cost :  3.1991868 
Prediction:
 [148.86075 186.40483 179.64806 196.01872 144.01079]
1280 Cost :  3.183019 
Pre