In [1]:
import tensorflow as tf

In [3]:
x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]
# 여러개의 클래스가 있으므로 한자리로 표현하는 것이 불가능 => one-hot encoding (하나만 핫하다)
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]] # 2,2,2,1,1,1,0,0

X = tf.placeholder("float",[None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3 # 클래스가 몇개인가

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') #들어오는건 4 나가는건 3
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# softmax = exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0 :
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    
    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1))) # arg_max함수 : 몇번째 있는게 가장 수가 큰가

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 7.859073
200 0.6599911
400 0.5419162
600 0.44674447
800 0.35577163
1000 0.26723742
1200 0.2255473
1400 0.20509925
1600 0.18791695
1800 0.17328611
2000 0.16068868
--------------
[[3.0651914e-03 9.9692541e-01 9.3802410e-06]] [1]
--------------
[[0.9010349  0.09078137 0.00818367]] [0]
--------------
[[2.2592335e-08 3.7704743e-04 9.9962294e-01]] [2]
--------------
[[3.0651914e-03 9.9692541e-01 9.3802410e-06]
 [9.0103489e-01 9.0781368e-02 8.1836712e-03]
 [2.2592335e-08 3.7704743e-04 9.9962294e-01]] [1 0 2]
