In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96.,98.,100.],[73.,66.,70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# shape 앞은 n개 이므로 None으로, 뒤는 한개의 리스트 당 개수
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = tf.matmul(X,W) + b

Instructions for updating:
Colocations handled automatically by placer.


In [3]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001) :
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_data, Y:y_data})
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction:\n", hy_val)

0 Cost :  1777.7031 
Prediction:
 [[113.33518]
 [140.37679]
 [136.57413]
 [146.28143]
 [109.68013]]
10 Cost :  1.7180252 
Prediction:
 [[150.61877]
 [185.1821 ]
 [180.72505]
 [194.36067]
 [143.85367]]
20 Cost :  1.6966003 
Prediction:
 [[150.7351 ]
 [185.3152 ]
 [180.85968]
 [194.50722]
 [143.95352]]
30 Cost :  1.6914628 
Prediction:
 [[150.73897]
 [185.31316]
 [180.8611 ]
 [194.50877]
 [143.95033]]
40 Cost :  1.6863397 
Prediction:
 [[150.7425 ]
 [185.3107 ]
 [180.86212]
 [194.50986]
 [143.94681]]
50 Cost :  1.68125 
Prediction:
 [[150.74602]
 [185.30827]
 [180.86317]
 [194.51097]
 [143.94331]]
60 Cost :  1.6761544 
Prediction:
 [[150.74951]
 [185.30582]
 [180.86418]
 [194.51207]
 [143.93979]]
70 Cost :  1.6711407 
Prediction:
 [[150.75298]
 [185.30339]
 [180.8652 ]
 [194.51315]
 [143.93631]]
80 Cost :  1.6661227 
Prediction:
 [[150.75647]
 [185.30098]
 [180.86624]
 [194.51425]
 [143.93283]]
90 Cost :  1.6611309 
Prediction:
 [[150.75995]
 [185.29858]
 [180.86725]
 [194.51537]
 [143.9

1090 Cost :  1.2715046 
Prediction:
 [[151.06186]
 [185.08807]
 [180.95522]
 [194.61401]
 [143.62366]]
1100 Cost :  1.2685331 
Prediction:
 [[151.06447]
 [185.08626]
 [180.95598]
 [194.61491]
 [143.621  ]]
1110 Cost :  1.2655401 
Prediction:
 [[151.06705]
 [185.08443]
 [180.9567 ]
 [194.61578]
 [143.61829]]
1120 Cost :  1.2625892 
Prediction:
 [[151.06964]
 [185.08261]
 [180.95746]
 [194.61668]
 [143.61563]]
1130 Cost :  1.2596436 
Prediction:
 [[151.07224]
 [185.08083]
 [180.95819]
 [194.61757]
 [143.61298]]
1140 Cost :  1.256726 
Prediction:
 [[151.07481]
 [185.07903]
 [180.95894]
 [194.61845]
 [143.61034]]
1150 Cost :  1.2538104 
Prediction:
 [[151.0774 ]
 [185.07722]
 [180.9597 ]
 [194.61932]
 [143.60767]]
1160 Cost :  1.2509269 
Prediction:
 [[151.07993]
 [185.07542]
 [180.96043]
 [194.6202 ]
 [143.60503]]
1170 Cost :  1.2480386 
Prediction:
 [[151.08249]
 [185.07364]
 [180.96118]
 [194.6211 ]
 [143.6024 ]]
1180 Cost :  1.2451669 
Prediction:
 [[151.08504]
 [185.07185]
 [180.9619 